language: node_js
node_js:
  - "8"
  - "node"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - cd skin
  - yarn install
script: echo HELLO
