language: node_js
node_js:
  - 8
  - node
cache:
  yarn: true
  directories:
    - skin/node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
 - 'if [ $TEST_SUITE = "skin" ]; then skin/ci/test.sh; fi'
 - 'if [ $TEST_SUITE = "skin-email-templates" ]; then skin/email-templates/ci/test.sh; fi'
env:
  matrix:
    - TEST_SUITE=skin
    - TEST_SUITE=skin-email-templates
