---
jobs:
- name: deploy-to-z
  serial: true
  plan:
  - aggregate:
    - get: govau-ci-console
      trigger: true
    - get: govau-cg-dashboard
      trigger: true
  - task: run-tests
    file: govau-ci-console/ci/tests.yml
  - put: z-cld-console
    params:
      manifest: govau-console/manifest.yml
      path: govau-console
      current_app_name: console

resources:
- name: govau-ci-console
  type: git
  source:
    uri: https://github.com/govau/ci-console
    branch: master
- name:  govau-cg-dashboard
  type: git
  source:
    uri: https://github.com/govau/cg-dashboard
    branch: z-cld
- name: z-cld-console
  type: cf
  source:
    api: https://api.system.z.cld.gov.au
    username: ci-system-console
    password: ((z-password))
    organization: system
    space: console
