---
jobs:
- name: test-and-deploy
  serial: true
  plan:
  - aggregate:
    - get: govau-ci-console
      trigger: true
    - get: govau-cg-dashboard
      trigger: true
  - task: run-tests
    file: govau-ci-console/ci/tests.yml
  - aggregate:
    - do:
      - task: prepare-manifest
        file: govau-ci-console/ci/prepare-manifest.yml
        input_mapping: {build: govau-console}
        output_mapping: {result: govau-console-g-cld}
        params:
          DOMAIN: system.g.cld.gov.au
      - put: g-cld-console
        params:
          manifest: govau-console-g-cld/manifest.yml
          path: govau-console
          current_app_name: console
    - do:
      - task: prepare-manifest
        file: govau-ci-console/ci/prepare-manifest.yml
        input_mapping: {build: govau-console}
        output_mapping: {result: govau-console-z-cld}
        params:
          DOMAIN: system.z.cld.gov.au
      - put: z-cld-console
        params:
          manifest: govau-console-z-cld/manifest.yml
          path: govau-console
          current_app_name: console

resources:
- name: govau-ci-console
  type: git
  source:
    uri: https://github.com/govau/ci-console
    branch: master
- name:  govau-cg-dashboard
  type: git
  source:
    uri: https://github.com/govau/cg-dashboard
    branch: z-cld
- name: g-cld-console
  type: cf
  source:
    api: https://api.system.g.cld.gov.au
    username: ci-system-console
    password: ((g-password))
    organization: system
    space: console
- name: z-cld-console
  type: cf
  source:
    api: https://api.system.z.cld.gov.au
    username: ci-system-console
    password: ((z-password))
    organization: system
    space: console
