---
jobs:
- name: console-dg
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        trigger: true
      - get: src
        trigger: true
    - task: run-tests
      file: ci/ci/tests.yml
    - aggregate:
      - do:
        - task: prepare-manifest
          file: ci/ci/prepare-manifest.yml
          output_mapping: {result: d-manifest}
          params:
            DOMAIN: system.d.cld.gov.au
        - put: d-cf
          params:
            manifest: d-manifest/manifest.yml
            path: build
            current_app_name: console
            show_app_log: true
      - do:
        - task: prepare-manifest
          file: ci/ci/prepare-manifest.yml
          output_mapping: {result: g-manifest}
          params:
            DOMAIN: system.g.cld.gov.au
        - put: g-cf
          params:
            manifest: g-manifest/manifest.yml
            path: build
            current_app_name: console
            show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-yz
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        passed: [console-dg]
      - get: src
        passed: [console-dg]
    - task: run-tests
      file: ci/ci/tests.yml
    - aggregate:
      - do:
        - task: prepare-manifest
          file: ci/ci/prepare-manifest.yml
          output_mapping: {result: y-manifest}
          params:
            DOMAIN: system.y.cld.gov.au
        - put: y-cf
          params:
            manifest: y-manifest/manifest.yml
            path: build
            current_app_name: console
            show_app_log: true
      - do:
        - task: prepare-manifest
          file: ci/ci/prepare-manifest.yml
          output_mapping: {result: z-manifest}
          params:
            DOMAIN: system.z.cld.gov.au
        - put: z-cf
          params:
            manifest: z-manifest/manifest.yml
            path: build
            current_app_name: console
            show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-b
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        passed: [console-yz]
      - get: src
        passed: [console-yz]
    - task: run-tests
      file: ci/ci/tests.yml
    - task: prepare-manifest
      file: ci/ci/prepare-manifest.yml
      output_mapping: {result: b-manifest}
      params:
        DOMAIN: system.b.cld.gov.au
    - put: b-cf
      params:
        manifest: b-manifest/manifest.yml
        path: build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/govau/ci-console
    branch: master

- name: src
  type: git
  source:
    uri: https://github.com/govau/cg-dashboard
    branch: deploy

- name: b-cf
  type: govau-cf
  source:
    api: https://api.system.b.cld.gov.au
    username: ci-system-console
    password: ((b-password))
    organization: system
    space: console

- name: d-cf
  type: govau-cf
  source:
    api: https://api.system.d.cld.gov.au
    username: ci-system-console
    password: ((d-password))
    organization: system
    space: console

- name: g-cf
  type: govau-cf
  source:
    api: https://api.system.g.cld.gov.au
    username: ci-system-console
    password: ((g-password))
    organization: system
    space: console

- name: y-cf
  type: govau-cf
  source:
    api: https://api.system.y.cld.gov.au
    username: ci-system-console
    password: ((y-password))
    organization: system
    space: console

- name: z-cf
  type: govau-cf
  source:
    api: https://api.system.z.cld.gov.au
    username: ci-system-console
    password: ((z-password))
    organization: system
    space: console

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: govau-cf
  type: docker-image
  source:
    repository: govau/cf-resource
    tag: tail
