---
jobs:

- name: console-d
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        trigger: true
      - get: src
        trigger: true
    - task: build
      file: ci/ci/build.yml
      output_mapping: {build: d-build}
      params:
        ENV_DOMAIN: d.cld.gov.au
    - put: d-cf
      params:
        manifest: d-build/manifest.yml
        path: d-build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-g
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        trigger: true
      - get: src
        trigger: true
    - task: build
      file: ci/ci/build.yml
      output_mapping: {build: g-build}
      params:
        ENV_DOMAIN: g.cld.gov.au
    - put: g-cf
      params:
        manifest: g-build/manifest.yml
        path: g-build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-y
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        passed: [console-d]
      - get: src
        passed: [console-d]
    - task: build
      file: ci/ci/build.yml
      output_mapping: {build: y-build}
      params:
        ENV_DOMAIN: y.cld.gov.au
    - put: y-cf
      params:
        manifest: y-build/manifest.yml
        path: y-build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-z
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        passed: [console-d]
      - get: src
        passed: [console-d]
    - task: build
      file: ci/ci/build.yml
      output_mapping: {build: z-build}
      params:
        ENV_DOMAIN: z.cld.gov.au
    - put: z-cf
      params:
        manifest: z-build/manifest.yml
        path: z-build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: console-b
  serial: true
  plan:
  - do:
    - aggregate:
      - get: ci
        passed: [console-y]
      - get: src
        passed: [console-y]
    - task: build
      file: ci/ci/build.yml
      output_mapping: {build: b-build}
      params:
        ENV_DOMAIN: b.cld.gov.au
    - put: b-cf
      params:
        manifest: b-build/manifest.yml
        path: b-build
        current_app_name: console
        show_app_log: true
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/govau/ci-console
    branch: master

- name: src
  type: git
  source:
    uri: https://github.com/govau/cg-dashboard
    branch: deploy

- name: b-cf
  type: govau-cf
  source:
    api: https://api.system.b.cld.gov.au
    username: ci-system-console
    password: ((b-password))
    organization: system
    space: console

- name: d-cf
  type: govau-cf
  source:
    api: https://api.system.d.cld.gov.au
    username: ci-system-console
    password: ((d-password))
    organization: system
    space: console

- name: g-cf
  type: govau-cf
  source:
    api: https://api.system.g.cld.gov.au
    username: ci-system-console
    password: ((g-password))
    organization: system
    space: console

- name: y-cf
  type: govau-cf
  source:
    api: https://api.system.y.cld.gov.au
    username: ci-system-console
    password: ((y-password))
    organization: system
    space: console

- name: z-cf
  type: govau-cf
  source:
    api: https://api.system.z.cld.gov.au
    username: ci-system-console
    password: ((z-password))
    organization: system
    space: console

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: govau-cf
  type: docker-image
  source:
    repository: govau/cf-resource
    tag: tail
